name: README Activity Updater

on:
  schedule:
    - cron: '* */1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: README Update on Recent Activity

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'README Activity History Has Been Updated! :'