name: WakaTime Dev Metric README Update

on:
  schedule:
    - cron: '30,30,30,30,30 0,6,12,18,0 * * *'

jobs:
  update-readme:
    name: Update README with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: False
          SHOW_EDITORS: False
          SHOW_LINES_OF_CODE: True
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False

